# Open config files with this editor, falls back to VISUAL and EDITOR environment variables
editor = "nano"

# Fallback values for game specific files without these:
[default]
# Use "Game ID" folder at this path
# Makes the path for game files "<game_root_path>/<gameID>"
game_root_path = "/mnt/games"
# Use "Game ID" folder at this path
# Makes the search path for mods "<mod_root_path>/<gameID>"
mod_root_path = "/mnt/mods"

# Default values for newly created game config files
[template]
# Pre-fill the path value with this value
path = "/home/username/.local/share/Steam/steamapps/common/"
# Pre-fill the mod_root_path with this value
mod_root_path = "/mnt/mods/"
